version: '3.4'

services:
  socialnetworking:
    image: ${DOCKER_REGISTRY-}socialnetworking
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_ENDPOINT = localhost
      - DB_NAME = social-networking
      - DB_USERNAME = postgres
      - DB_PASSWORD = postgres
      - DB_PORT = 5431
    build:
      context: .
      dockerfile: SocialNetworking/Dockerfile
    ports:
        - "5000:80"
    restart: on-failure

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "social-networking"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
